spring:
  application:
    name: trip-planning-service
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  cache:
    cache-names: currencyRates
    caffeine:
      spec: maximumSize=32,expireAfterWrite=12h,recordStats

navio:
  currency-provider:
    base-url: https://api.frankfurter.dev
  mobility:
    base-url: ${MOBILITY_SERVICE_BASE_URL:http://localhost:8083}

management:
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: http://localhost:9411/api/v2/spans
  prometheus:
    metrics:
      export:
        enabled: true
